### ISSUE TITLE
Automatic Chat Clearing

### ISSUE THREAD

**Issue by ZeroXNoxus** [illandril/FoundryVTT-chat-enhancements#157]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem caused by your module, but by Foundry itself. I've created a script to automatically prune the chat log and lighten the initial load into a game.

**Describe the solution you'd like**
A friend of mine had the problem that the initial load took several minutes at times and the issue was caused by an excessive amount of chat messages. I though of a solution which automatically deletes messages.

Here's the code:
`Hooks.once("init", function(){
	game.settings.register('auto-clear-messages', 'delete-at-length', {
		name: 'When to clear chat messages?',
		label: 'When to clear chat messages?',
		type: Number,
		default: 1000
	});
	game.settings.register('auto-clear-messages', 'clear-amount', {
		name: 'How many messages should be cleared?',
		label: 'How many messages should be cleared?',
		type: Number,
		default: 500
	});
	const length = $('#chat-log').find('li.chat-message').length;
	const delAtLength = game.settings.get('auto-clear-messages', 'delete-at-length');
	if(delAtLength !== 0){
		const amount = game.settings.get('auto-clear-messages', 'clear-amount')
		let i = 0;
		if(length >= delAtLength){
			game.messages.forEach(function(m){
					if(i !== amount){
						m.delete();
						i++;
					};
			});
		};
	};
});`

I would love to see you implement this feature into your module, maybe by additionally providing a boolean to enabled/disable this feature. It would likely help a lot of people that do have the same issue that my friend had. I can also create my own module, but yours has way more bandwidth, so I think it would be suited better here.

**Comment by illandril** [comment]
This issue might be solved already in the latest Foundry - it only loads the last 100 messages initially, and only loads more if you scroll up to see them.

Do you still see the slowness in Foundry v11 Build 315?
I'm able to load a world with 81k chat messages without any noticeable slowness.

If you do still see the issue, which of the following solutions would you prefer?
1. Automatically deleting the oldest message(s) whenever a new message is created and there are more than N total messages
2. Replacing the "Clear Chat Log" button with a "Clean Chat Log" button that asks for the number of messages to keep instead of being "all or nothing".
3. Automatically deleting messages older than N days whenever a GM logs in, and every 30 minutes (until the GM logs out or closes their browser)
4. Replacing the "Clear Chat Log" button with a "Clean Chat Log" button that asks for a date, and deletes all chat messages before that date
5. Replacing the "Clear Chat Log" button with a "Clean Chat Log" button that asks for a date and time, and deletes all chat messages before that date-time

**Comment by ZeroXNoxus** [comment]
The Error occured with the newest stable Foundry Release (11.315). I still don't know why it only happened for my friend, but after pruning the 116K messages the Game loaded for him lickety-split. 

I'd say three settings should be present for this:
- a bool to select If the chat should be automatically cleaned
- Message trigger amount (eg. 1000) as a Number
- Message clear target (eg. 500) as a Number (how many messages should be left after clearing)
- (optional) bool to Archive the messages with the current Date instead of only deleting

The check should be made on an Initial load for the GM.

You could also add a dropdown with different settings for the Message clear options an include more of the options you've suggested.

Thanks for looking into this ♥️
